name = "iter-curriculum"
compatibility_date = "2024-12-01"

[build]
command = ""
publish = "."

[build.environment_variables]
NODE_VERSION = "18"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[env.production]
route = { pattern = "iter-curriculum.pages.dev", zone_name = "pages.dev" }

[env.production.vars]
ENVIRONMENT = "production"
