name = "iter-curriculum"
compatibility_date = "2024-12-01"

[build]
command = ""
publish = "."

[build.environment_variables]
NODE_VERSION = "18"

# Headers for performance and security
[[headers]]
pattern = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), payment=(), usb=(), interest-cohort=()"
X-Robots-Tag = "index, follow"

# Cache headers for static assets
[[headers]]
pattern = "/images/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
pattern = "/*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
pattern = "/*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
pattern = "/*.webp"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# SEO headers for main page
[[headers]]
pattern = "/"
[headers.values]
Link = "</sitemap.xml>; rel=sitemap; type=application/xml"

# SEO-friendly redirects
[[redirects]]
from = "/curriculum"
to = "/"
status = 301

[[redirects]]
from = "/syllabus"
to = "/"
status = 301

[[redirects]]
from = "/iter"
to = "/"
status = 301

# Main SPA fallback
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[env.production]
route = { pattern = "iter-curriculum.pages.dev", zone_name = "pages.dev" }

[env.production.vars]
ENVIRONMENT = "production"
